name: Call Reusable Build

on:
  push:
    branches:
    - main

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/called_workflow_1.yml
    with:
      packer_version: '1.8.5'
      build_name: 'TestBuild'
