
name: Build Reusable

on:
  workflow_call:
    inputs:
      packer_version:
        description: 'Version of Packer to use'
        required: true
        type: string
      build_name:
        description: 'Name of the build'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Simulate Packer Build
      run: echo "Simulating build for ${{ inputs.build_name }} using Packer version ${{ inputs.packer_version }}"
